### ISSUE TITLE
How to find the model architecture for 913base.pkl?

### ISSUE THREAD

**Issue by Sakurajima-sight** [agao8/STEAD#3]
Hello,

I would like to use the `913base.pkl` file, which contains the pretrained weights for the model. However, I am unable to find the definition of the model architecture in the repository. Could you please guide me to where the model architecture is defined?

Thank you for your help!

**Comment by agao8** [comment]
Hello,

I've pushed an update that adds the option to specify whether to use the base or tiny/fast architecture. You can find the option in options.py. Note that you still need to specify the pretrained weights from within test.py.

**Comment by song248** [comment]
Hello,

I have modified option.py.
However, I don't quite understand what you mean by needing to specify the pretrained weights manually.
I updated the model loading part in test.py, but I'm still getting a size mismatch error.
